# Bg color
BLUESKY = (210, 224, 251)

# Number of blocks in the matrix
GRID_SIZE = 10

TEXTBOX_HEIGHT = 80
WINDOW_SIZE = 700
MATRIX_SIZE = GRID_SIZE + 2
CELL_SIZE = (WINDOW_SIZE // MATRIX_SIZE)
WINDOW_HEIGHT = (CELL_SIZE * MATRIX_SIZE) + TEXTBOX_HEIGHT
